version: "3.9"
services:
  api:
    build: backend/.
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    restart: always
    environment:
      - POSTGRES_HOST=postgres # specify ip address, avoid using 'localhost'
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SSL_MODE=${SSL_MODE}
      - GO_MOVIES_JWT=${GO_MOVIES_JWT}

  client:
    build: frontend/.
    ports:
      - "3000:3000"

  postgres:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
       - ./db/imports/init.sql:/docker-entrypoint-initdb.d/init.sql